spring:
  datasource:
    url: jdbc:mysql://mysql:3306/myappdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
        connection:
          characterEncoding: UTF-8
          useUnicode: true
  thymeleaf:
    encoding: UTF-8

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true 